FROM maven:3.9-eclipse-temurin-17 AS transactionunit-build
WORKDIR /transactionunit
COPY pom.xml pom.xml
COPY src/main ./src/main
RUN mvn -Dmaven.repo.local=./m2 -B install

FROM maven:3.9-eclipse-temurin-17 AS war-build
WORKDIR /war
COPY --from=transactionunit-build /transactionunit/m2 ./m2
COPY target/test-classes/wildfly-pom.xml pom.xml
COPY src/test/wildfly/src ./src
RUN mvn -Dmaven.repo.local=/war/m2 -B -q -Ptransactionunit package

FROM quay.io/wildfly/wildfly:36.0.1.Final-jdk17
ENV ORG_TRANSACTIONUNIT_PERSISTENCE_PROVIDER="org.hibernate.jpa.HibernatePersistenceProvider"
COPY --from=war-build /war/target/ROOT.war /opt/jboss/wildfly/standalone/deployments/
